name: ci

on:
  push:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install apt packages
        run: ./install-packages.sh

      - name: build jlab app
        run: ./build-jlab.sh
